### ISSUE TITLE
cannot make

### ISSUE THREAD

**Issue by andanders** [sambazley/virtjs#1]
I want to use my Thrustmaster T-rudder pedals with steam, but when I run the command

`$ make virtjs /dev/input/js1`
I get the error
```bash
make: pkgconf: No such file or directory
cc -Wall -Wextra -Wpedantic -Werror    -c -o virtjs.o virtjs.c
virtjs.c:20:10: fatal error: libevdev/libevdev.h: No such file or directory
   20 | #include <libevdev/libevdev.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: virtjs.o] Error 1
``` 
I did install libevdev-dev first.

OS: Pop!_OS 22.04 LTS

**Comment by sambazley** [comment]
```make: pkgconf: No such file or directory```

You need to install pkgconf.

**Comment by andanders** [comment]
Noob alert. I hardly every compile from source. I installed pkgconf and Make ran. Now I'm looking at the virtjs and .o  and wondering what to do with it. 
But I'm afraid it failed. Output was:
```bash
make virtjs /dev/input/by-id/usb-Thrustmaster_T-Rudder_00000000001A-event-if00
cc -Wall -Wextra -Wpedantic -Werror -I/usr/include/libevdev-1.0/    -c -o virtjs.o virtjs.c
cc   virtjs.o  -levdev  -o virtjs
make: Nothing to be done for '/dev/input/by-id/usb-Thrustmaster_T-Rudder_00000000001A-event-if00'.
```
and virtjs.o contains (I used cat, not sure how to read .o property)
```bash
ailed to init libevdev: %s
%s (%04x:%04x)
This device has buttons
This device does not have absolute axes
/dev/uinputVirtual JoystickFailed to create device
GCC: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0GNU�zRx
E                                               E�C
J����C
   ��
�%*1BW`x��������5�KRfkyvirtjs.csigintmainstderrfprintfopenperror__errno_locationlibevdev_new_from_fdstrerrorlibevdev_get_id_productlibevdev_get_id_vendorlibevdev_get_namelibevdev_has_event_typefwritememsetstrncpyioctllibevdev_has_event_codelibevdev_get_abs_minimumlibevdev_get_abs_maximumlibevdev_get_abs_flatlibevdev_get_abs_fuzzsignallibevdev_next_eventpolllibevdev_freeclose__stack_chk_fail|
```

**Comment by sambazley** [comment]
You can just run `make` to compile the virtjs binary. Once the binary has been compiled you can then run virtjs as shown in the readme. The `./` prefix is not optional as that tells your shell that the binary is in the current directory and not in $PATH.

**Comment by andanders** [comment]
Right! The device is showing up as an xbox controller. 
Much appreciated Sam.
